name: "DATA ANALYSIS"
output_dir: "docs"
navbar:
  title: "DATA ANALYSIS"
  left:
    - text: "Home"
      href: "index.html"
    - text: "About"
      href: "about.html"
output:
  html_document:
    theme: "bootstrap"
    toc: true
    toc_float: true
